apiVersion: config.openshift.io/v1
kind: Build
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
spec: {}
